CREATE TABLE `lc_requests` (
	`request_id` varchar(32) NOT NULL,
	`requester_name` varchar(255) NOT NULL DEFAULT '',
	`requester_email` varchar(320) NOT NULL DEFAULT '',
	`department` varchar(255) NOT NULL DEFAULT '',
	`request_type` varchar(255) NOT NULL DEFAULT '',
	`priority` varchar(64) NOT NULL DEFAULT '',
	`deadline` varchar(64) NOT NULL DEFAULT '',
	`description` text,
	`doc_link` text,
	`counter_party` varchar(512) NOT NULL DEFAULT '',
	`customer_type` varchar(255) NOT NULL DEFAULT '',
	`ip_product` varchar(255) NOT NULL DEFAULT '',
	`biz_segment` varchar(255) NOT NULL DEFAULT '',
	`pnl_owner` varchar(255) NOT NULL DEFAULT '',
	`region` varchar(255) NOT NULL DEFAULT '',
	`current_status` varchar(128) NOT NULL DEFAULT 'request-raised',
	`status_note` text,
	`history_json` text,
	`status_updated_by` varchar(320) NOT NULL DEFAULT '',
	`requested_by` varchar(320) NOT NULL DEFAULT '',
	`is_confidential` int NOT NULL DEFAULT 0,
	`submitted_at` varchar(64) NOT NULL DEFAULT '',
	`updated_at` varchar(64) NOT NULL DEFAULT '',
	CONSTRAINT `lc_requests_request_id` PRIMARY KEY(`request_id`)
);
