export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  qbGoogleClientId: process.env.QB_GOOGLE_CLIENT_ID ?? "",
  qbGoogleClientSecret: process.env.QB_GOOGLE_CLIENT_SECRET ?? "",
  qbSessionSecret: process.env.QB_SESSION_SECRET ?? "qb-session-secret",
  bqOAuthClientId: process.env.BQ_OAUTH_CLIENT_ID ?? "",
  bqOAuthClientSecret: process.env.BQ_OAUTH_CLIENT_SECRET ?? "",
  bqOAuthRefreshToken: process.env.BQ_OAUTH_REFRESH_TOKEN ?? "",
};
